version: '2.4'
services:
  mongodb:
    image: mongo:3.4
    ports:
      - 27017:27017
    volumes:
      - ./tmp-docker-vol/mongodb:/data/db
  ai-bot:
    privileged: true
    build: .
    volumes:
      - ../ai-bot:/usr/src/app
    ports:
      - 3000:3000
      - 8080:8080
    links:
      - mongodb
    environment:
    - ENV=local
    - MONGO_URL=mongodb://mongodb:27017/intentDB?retryWrites=true&w=majority
    - MONGO_URL_TEST=mongodb://mongodb:27017/testIntentDB?retryWrites=true&w=majority
    - API_KEY=825765d4-7f8d-4d83-bb03-9d45ac9c27c0
    command: bash -c "npm i && bash ./docker/run.sh"

